### PR TITLE
feat:added handle fill selection and copy funtionality

### PR DESCRIPTION
**Pull request by rajeshj11**
/claim #533 

demo video:
https://www.loom.com/share/c55985690fb542bb95d1aaba08b1845b

### CODE REVIEW

**Comment by rajeshj11** [comment]
@harinij Please check the demo video. let me know if any changes are needed.

**Comment by rajeshj11** [comment]
@harinij @bofeiw I just wanted to give a gentle nudge on this pull request as it's been a little while since I submitted it. Whenever you get a chance, I would greatly appreciate your feedback.

Thank you for your time and consideration!

**Comment by harinij** [comment]
HI @rajeshj11 - thanks for the contribution, we will be reviewing this in depth soon in our upcoming cycle and share feedback.

In the meantime I just noticed the color theme of the dot and selection etc did not match the theme of the app. Could you take a look or let us know if you need further guidance.

**Comment by rajeshj11** [comment]
Hi @harinij 
Thanks for letting me know about the color issue with the dots and selection in the app. I've checked it out.

To fix it properly, could you please give me more info about how you want the colors to match? Any extra details you can share will help us make the app look better. (if possible provide me a screenshot of how it should look like)

**Comment by rajeshj11** [comment]
@harinij 
 I've implemented changes to ensure that the color theme of the dot and selection align dynamically with the user's chosen theme within the app.

Could you please review this demo video to confirm if these adjustments meet your expectations? If further refinements are needed, I'm more than happy to accommodate them. Your guidance is greatly appreciated in ensuring we meet your requirements seamlessly.

https://www.loom.com/share/0cf2eafcca6e42ed893d85cfbdab60eb

**Comment by harinij** [comment]
Hey @rajeshj11 - thanks for the contribution. Looking at the demo and video there is a mismatch in the design theme and colors. For now we will be closing this PR but as a token of appreciation for your work we will add a tip shortly. Thanks

**Pull request closed without merging**
