### PR TITLE
add multi filters support

### LINKED ISSUE #582: Multiple filters support
**Is your feature request related to a problem? Please describe.**

We need to be able to have multiple filters applied to a view. Indexes have to be created either automatically (via rowyRun) or it should prompt a link to generate them.

### PR DESCRIPTION
**Pull request by mnmt7**
Fixes #582 
/claim #582

### CODE REVIEW

**Comment by harinij** [comment]
@mnmt7 I see build failure on this, are you seeing this when you try locally? Adding error log here
Screenshot 2023-06-20 at 2 55 26 pm

**Comment by mnmt7** [comment]
@harinij I have fixed the error. Please have a look when you have time.

**Comment by harinij** [comment]
@mnmt7 it is building and working locally? Because I see other build issues now, screenshot here: 
Screenshot 2023-06-27 at 2 34 29 pm

**Comment by mnmt7** [comment]
@harinij I have fixed the errors and it should work now. 

[Screencast from 2023-06-28 21-27-51.webm](https://github.com/rowyio/rowy/assets/107614965/8f67d2b4-08e2-4710-b66f-f44d0a9bc2ec)

**Comment by harinij** [comment]
Hi @mnmt7 this PR has some deployment issues and conflicts due to which we are unable to merge. Also, because it has had multiple updates it results in the build failing. If you can submit a new PR with all the latest changes for this it would be much easier to build and merge this. Thank you.

**Comment by il3ven** [comment]
@harinij Is creation of firebase index part of this task? Ranged filter queries require an index. For example, if we want to filter for rows with age greater than 18. We see the following error message.

**Comment by harinij** [comment]
@il3ven In case an index is missing, user can click on the link in the snackmessage and create one manually. This part need not be automated for now.

**Comment by il3ven** [comment]
@mnmt7 I see that you have introduced a new `id` field to the `TableFilter` schema. I understand why it was needed but it is breaking backward compatibility.

If a user has a filter already applied to a table then the filter functionality breaks. See the below video.

https://github.com/rowyio/rowy/assets/4337699/d96b7fd0-6c5d-4396-bf03-2ebe53bb6a90

> Here I have a table with a filter which I created using the main branch. I then checked to your branch.

It happens because the existing filter stored in firebase is missing the `id` field. We'll need to think of some alternatives. Either ditch `id` or add it to the stored filter if missing.

**Comment by harinij** [comment]
Closing this as per note by @il3ven and new PR submitted #1390

**Pull request closed without merging**
