### PR TITLE
fix: FEAT: Array column should be filterable

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix: #1382
/claim #1382

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@harinij @shamsmosowi

Can you take a look? I've extended every method in firestore for arrays: https://firebase.google.com/docs/firestore/query-data/queries#array_membership

Works locally just as fine.

**Comment by il3ven** [comment]
@rishi-raj-jain First of all, thank you for the efforts. Second, the PR needs to be opened against develop. You'll need to rebase. Third, this PR isn't working for all cases. To reproduce, use "not-includes" as the operator.

I believe it isn't working because the translation from `value` to firebase query is missing. It should be done here.

https://github.com/rowyio/rowy/blob/b2983f4db82ebc6c2ad526410a8d20088cc0f245/src/hooks/useFirestoreCollectionWithAtom.ts#L386-L398

**Comment by rishi-raj-jain** [comment]
Thanks for pointing that out.
So I see this only failing for both includes and non-includes. The rest seem to work fine.
By against develop you mean from my develop to rowy's develop, right? Right now, it's from my main to your's develop.

**Comment by il3ven** [comment]
> So I see this only failing for both includes and non-includes. The rest seem to work fine.

Yes

> By against develop you mean from my develop to rowy's develop, right? Right now, it's from my main to your's develop.

The name of your branch can be anything. It doesn't have to be develop. Let's say your branch name is *rishi*. The PR will be from rishi to develop.  However, *rishi* should have all the commits from rowy's develop plus your new commits. Otherwise, there will be merge conflicts which we can see right now.

There are different ways to do this.
- You can create a new branch from develop and cherry-pick the new commits from rishi-raj-jain:main.
- Don't create a new branch but do `git rebase develop` to your current branch.

**Comment by rishi-raj-jain** [comment]
@il3ven 

Thanks for the answers. I do realize it's not the same but the branch. 

I figured out that in and not-in don't work when we want to filter when the filter value is an array itself.

Only, ==, !=, array-contains and array-contains-any are the supported methods as I gather from that link + testing in a simple demo.js file.

**Comment by rishi-raj-jain** [comment]
Creating a fresh PR.

**Pull request closed without merging**
