### PR TITLE
fix: fixed paste on text field error

### LINKED ISSUE #1523: BUG: copy/paste on Array Subtable filed gives an incorrect error
**Describe the bug**

Copy/pasting on array subtable has some issues. 

Issue 1
Copy/pasting the array subtable field is throws an error:
Screenshot 2024-01-22 at 19 06 57

Issue 2
Copying fields inside array subtable works.
Pasting fields inside array subtable works but an error is displayed.
Screenshot 2024-01-22 at 19 07 16

**To Reproduce**
1. On Rowy - create an array subtable field
2. Copy or paste the field, see issue 1
3. Go in to the subtable, create a text column and add a row
4. Paste some values in the text cell, see issue 2

**Expected behaviour**

The data type of [Array SubTable](https://docs.rowy.io/field-types/array-subtable) in FIrestore is [array of maps](https://firebase.google.com/docs/firestore/manage-data/data-types).
Issue 1: copy/paste on the array subtable should copy the array to clipboard or write values to Firestore, similar how JSON field works.

Issue 2: pasting into the fields inside subtable should continue to work without any errors displayed.

### PR DESCRIPTION
**Pull request by anikdhabal**
Fixes #1523 
/claim #1523

### CODE REVIEW

**Comment by harinij** [comment]
Thanks @anikdhabal for the PR - can you share a before and after video to show it working plus showing if paste works fine in other fields as well.

**Comment by anikdhabal** [comment]
> Thanks @anikdhabal for the PR - can you share a before and after video to show it working plus showing if paste works fine in other fields as well.

Yeah, let me share it quickly.

**Review by bofeiw — CHANGES_REQUESTED** [review]
This does not resolve the issues described in the updated [issue description](https://github.com/rowyio/rowy/issues/1523), please update.

**Comment by anikdhabal** [comment]
https://github.com/rowyio/rowy/assets/81948346/6e08d4e9-72f4-4579-9859-74bd363cf4cf

@harinij @bofeiw It's working fine now. I've attached the result.

**Comment by anikdhabal** [comment]
@harinij @bofeiw could you review it once?

**Review by bofeiw — CHANGES_REQUESTED** [review]
@anikdhabal  issue 1 (pasting outside array subtable) is resolved, however issue 2 (pasting into cells into array subtable) persists, please take a look.

Pasting into a short text will throw an error:
Screenshot 2024-01-26 at 07 16 33


Pasting into a number will overwrite the whole array subtable field and crash the page:
Screenshot 2024-01-26 at 07 16 42
Screenshot 2024-01-26 at 07 18 02


Please check and make sure pasting into all supported fields inside array subtable works.

**Comment by anikdhabal** [comment]
Hey @bofeiw I've updated the code, and now both issues are resolved.

**Comment by bofeiw** [comment]
Upon testing, issue 2 still persists. 
Closing this as fixed in https://github.com/rowyio/rowy/pull/1536

**Pull request closed without merging**
