### PR TITLE
#513: Added Customizable Icons for Ratings Field

### PR DESCRIPTION
**Pull request by mshamsrainey**
#513: Added Customizable Icons for Rating Field

Demonstration here (no audio): https://www.loom.com/share/b4738b9a8a4e45e0bd9c945d9a203388 (Video demo updated to reflect side drawer and icon size updates)

Note: While working on this ticket, I encountered a bug that I created an issue for here #816. I also received some great design feedback that I wish I had time to work on, but don't think I will at the moment (at least during this one day open source challenge!).

### CODE REVIEW

**Comment by shamsmosowi** [comment]
Hi @mshamsrainey, this looks great! 
in terms of the use of the preview fab icon button, it makes sense in the context of the action button, but here it would be more informative for the user to preview how the cell interaction is going to look

**Comment by mshamsrainey** [comment]
@shamsmosowi great call, thanks for that feedback! I'll take a look at making that change either tonight or tomorrow and ping you for another review when I'm finished

**Comment by mshamsrainey** [comment]
Hi @shamsmosowi, I just pushed a new commit changing the settings to give a preview of how the ratings will look using the custom icons. 

While working on this, I also realized that the existing code would allow people to leave the text field indicating what they wanted their maximum rating to be blank, or set the maximum rating to something super high like 10,000. So, I added in some simple validation to restrict users to a range 1-20 based on the input props already present in the code.

Let me know what you think!

**Review by notsidney — CHANGES_REQUESTED** [review]
This looks good!

You should use the current `StarBorderIcon` as the default `emptyIcon`, as it’s higher contrast and improves accessibility.

image

**Comment by notsidney** [comment]
@mshamsrainey Thanks! I’m merging this now and it will be part of the next release 🚀

**Pull request merged**
