### PR TITLE
fixed-issue #533

### PR DESCRIPTION
**Pull request by Ali7040**
drag and drop issue solved 

https://github.com/rowyio/rowy/assets/81979505/da3d574c-b779-445a-9e98-e984b5834d59

/claim #533

### CODE REVIEW

**Comment by Ali7040** [comment]
@harinij, if there's any problem with the PR, please let me know, and I will try to solve it.

**Comment by harinij** [comment]
Hi @Ali7040 thanks for the attempt and PR. The issue actually was meant for drag and drop fill like in a typical spreadsheet. For example in google docs, you are able to do it like this video attached. Do let us know if any additional info is needed.

https://github.com/rowyio/rowy/assets/307298/1422a0bf-f08c-4859-987b-baf29c8fc7c8

**Comment by Ali7040** [comment]
Thanks for letting me know!

**Comment by Ali7040** [comment]
@harinij To enable this feature, we need to work with AG Grid. React Table does not support this feature. 
image

**Comment by Ali7040** [comment]
@harinij  React Table only supports Dnd (Drag-and-Drop).

**Comment by harinij** [comment]
Hi @Ali7040 thanks for sharing additional info. In that case will mark this as out of scope with the current React Table implementation.

**Pull request closed without merging**
